# server configurations
hostname = 'localhost'
port = '9443'

#Key manager server configurations
km_hostname = 'localhost'
km_port = '9443'

#REST clients configurations
adminVersion = 'v0.17'
publisherVersion = 'v1'
restapi = 'publisher' # use publisher or store rest api

#API calls configurations
expand = true
limit = 500
offset = 0
query = 'status:PUBLISHED'

# admin credentials
username = 'admin'
password = 'admin'

# dynamic client registration
[dynamic_client_registration]
callbackUrl = 'www.google.lk'
clientName = 'rest_api_publisher'
owner = 'admin'
grantType = 'client_credentials password refresh_token'
saasApp = true

# access token generation configurations
[access_token]
grant_type = 'password'
scope = 'apim:subscribe apim:api_create apim:api_view apim:api_publish'

# winston logger configurations
[log]
source = './repository/logs/'

# winston logger debug configurations
[debug]
debug = false
response = false

# misc settings
[misc]
timeout = 5000