# server configurations
hostname = 'localhost'
port = '9443'
km_hostname = 'localhost'
km_port = '9443'
version = 'v0.14'

expand = true
limit = 200
offset = 0
query = 'status:PUBLISHED'

# admin credentials
username = 'admin'
password = 'admin'

# dynamic client registration
[dynamic_client_registration]
callbackUrl = 'www.google.lk'
clientName = 'rest_api_store'
owner = 'admin'
grantType = 'password refresh_token'
saasApp = true

# access token generation configurations
[access_token]
grant_type = 'password'
scope = 'apim:subscribe apim:api_create apim:api_view apim:api_publish'

# winston logger configurations
[log]
source = './repository/logs/'

# winston logger debug configurations
[debug]
debug = false
response = false

# misc settings
[misc]
timeout = 5000